import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

// Importar la nueva fuente
const roboto = localFont({
  src: "/fonts/Roboto-Regular.woff2", // Asegúrate de que la ruta sea correcta
  variable: "--font-roboto",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}